server:
        port: 9090
spring:
        application:
               name: zuul-gateway        
        cloud: 
          gateway:
            globalcors:
               corsConfigurations:'[/**]':
                 allowedOrigins: "http://localhost:3000"
                 allowedHeaders: "*"
                 allowedMethods: "*"
            routes:
            - id: admin-service
              uri: http://localhost:8081/
              predicates:
              - Path=/admin-service/**
              filters:
              - StripPrefix=1
            - id: doctor-service
              uri: http://localhost:8082/
              predicates:
              - Path=/doctor-service/**
              filters:
              - StripPrefix=1
            - id: drug-inventory-service
              uri: http://localhost:8084/
              predicates:
              - Path=/drug-inventory-service/**  
              filters:
              - StripPrefix=1
            - id: supplier-inventory-service
              uri: http://localhost:8085/
              predicates:
              - Path=/supplier-inventory-service/**
              filters:
              - StripPrefix=1 
            - id: order-service
              uri: http://localhost:8083/
              predicates:
               - Path=/order-service/**
              filters:
              - StripPrefix=1
            - id: pickup-service
              uri: http://localhost:8070/
              predicates:
               - Path=/pickup-service/**
              filters:
              - StripPrefix=1   
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true






            
     
            
           
          


              




